package com.peace.entity;

import java.io.Serializable;
import java.util.Date;

public class PushError implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_push_error.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_push_error.user_id
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_push_error.error_type
     *
     * @mbg.generated
     */
    private Integer errorType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_push_error.error
     *
     * @mbg.generated
     */
    private String error;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_push_error.again_push_type
     *
     * @mbg.generated
     */
    private Integer againPushType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_push_error.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_push_error.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_push_error.update_by
     *
     * @mbg.generated
     */
    private Long updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_push_error.user_name
     *
     * @mbg.generated
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_push_error.sqcode
     *
     * @mbg.generated
     */
    private String sqcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_push_error
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_push_error.id
     *
     * @return the value of t_push_error.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_push_error.id
     *
     * @param id the value for t_push_error.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_push_error.user_id
     *
     * @return the value of t_push_error.user_id
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_push_error.user_id
     *
     * @param userId the value for t_push_error.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_push_error.error_type
     *
     * @return the value of t_push_error.error_type
     *
     * @mbg.generated
     */
    public Integer getErrorType() {
        return errorType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_push_error.error_type
     *
     * @param errorType the value for t_push_error.error_type
     *
     * @mbg.generated
     */
    public void setErrorType(Integer errorType) {
        this.errorType = errorType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_push_error.error
     *
     * @return the value of t_push_error.error
     *
     * @mbg.generated
     */
    public String getError() {
        return error;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_push_error.error
     *
     * @param error the value for t_push_error.error
     *
     * @mbg.generated
     */
    public void setError(String error) {
        this.error = error == null ? null : error.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_push_error.again_push_type
     *
     * @return the value of t_push_error.again_push_type
     *
     * @mbg.generated
     */
    public Integer getAgainPushType() {
        return againPushType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_push_error.again_push_type
     *
     * @param againPushType the value for t_push_error.again_push_type
     *
     * @mbg.generated
     */
    public void setAgainPushType(Integer againPushType) {
        this.againPushType = againPushType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_push_error.create_time
     *
     * @return the value of t_push_error.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_push_error.create_time
     *
     * @param createTime the value for t_push_error.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_push_error.update_time
     *
     * @return the value of t_push_error.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_push_error.update_time
     *
     * @param updateTime the value for t_push_error.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_push_error.update_by
     *
     * @return the value of t_push_error.update_by
     *
     * @mbg.generated
     */
    public Long getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_push_error.update_by
     *
     * @param updateBy the value for t_push_error.update_by
     *
     * @mbg.generated
     */
    public void setUpdateBy(Long updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_push_error.user_name
     *
     * @return the value of t_push_error.user_name
     *
     * @mbg.generated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_push_error.user_name
     *
     * @param userName the value for t_push_error.user_name
     *
     * @mbg.generated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_push_error.sqcode
     *
     * @return the value of t_push_error.sqcode
     *
     * @mbg.generated
     */
    public String getSqcode() {
        return sqcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_push_error.sqcode
     *
     * @param sqcode the value for t_push_error.sqcode
     *
     * @mbg.generated
     */
    public void setSqcode(String sqcode) {
        this.sqcode = sqcode == null ? null : sqcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_push_error
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        PushError other = (PushError) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getErrorType() == null ? other.getErrorType() == null : this.getErrorType().equals(other.getErrorType()))
            && (this.getError() == null ? other.getError() == null : this.getError().equals(other.getError()))
            && (this.getAgainPushType() == null ? other.getAgainPushType() == null : this.getAgainPushType().equals(other.getAgainPushType()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getUpdateBy() == null ? other.getUpdateBy() == null : this.getUpdateBy().equals(other.getUpdateBy()))
            && (this.getUserName() == null ? other.getUserName() == null : this.getUserName().equals(other.getUserName()))
            && (this.getSqcode() == null ? other.getSqcode() == null : this.getSqcode().equals(other.getSqcode()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_push_error
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getErrorType() == null) ? 0 : getErrorType().hashCode());
        result = prime * result + ((getError() == null) ? 0 : getError().hashCode());
        result = prime * result + ((getAgainPushType() == null) ? 0 : getAgainPushType().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getUpdateBy() == null) ? 0 : getUpdateBy().hashCode());
        result = prime * result + ((getUserName() == null) ? 0 : getUserName().hashCode());
        result = prime * result + ((getSqcode() == null) ? 0 : getSqcode().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_push_error
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", errorType=").append(errorType);
        sb.append(", error=").append(error);
        sb.append(", againPushType=").append(againPushType);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", updateBy=").append(updateBy);
        sb.append(", userName=").append(userName);
        sb.append(", sqcode=").append(sqcode);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}