package com.peace.entity;

import java.io.Serializable;
import java.util.Date;

public class Task implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_to_do_list.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_to_do_list.org_code
     *
     * @mbg.generated
     */
    private String orgCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_to_do_list.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_to_do_list.user_account
     *
     * @mbg.generated
     */
    private String userAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_to_do_list.user_name
     *
     * @mbg.generated
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_to_do_list.role_id
     *
     * @mbg.generated
     */
    private Long roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_to_do_list.role_code
     *
     * @mbg.generated
     */
    private String roleCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_to_do_list.today_num
     *
     * @mbg.generated
     */
    private Long todayNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_to_do_list.seven_days_num
     *
     * @mbg.generated
     */
    private Long sevenDaysNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_to_do_list.overdue_num
     *
     * @mbg.generated
     */
    private Long overdueNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_to_do_list.create_date
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sales_to_do_list
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_to_do_list.id
     *
     * @return the value of sales_to_do_list.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_to_do_list.id
     *
     * @param id the value for sales_to_do_list.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_to_do_list.org_code
     *
     * @return the value of sales_to_do_list.org_code
     *
     * @mbg.generated
     */
    public String getOrgCode() {
        return orgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_to_do_list.org_code
     *
     * @param orgCode the value for sales_to_do_list.org_code
     *
     * @mbg.generated
     */
    public void setOrgCode(String orgCode) {
        this.orgCode = orgCode == null ? null : orgCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_to_do_list.user_id
     *
     * @return the value of sales_to_do_list.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_to_do_list.user_id
     *
     * @param userId the value for sales_to_do_list.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_to_do_list.user_account
     *
     * @return the value of sales_to_do_list.user_account
     *
     * @mbg.generated
     */
    public String getUserAccount() {
        return userAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_to_do_list.user_account
     *
     * @param userAccount the value for sales_to_do_list.user_account
     *
     * @mbg.generated
     */
    public void setUserAccount(String userAccount) {
        this.userAccount = userAccount == null ? null : userAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_to_do_list.user_name
     *
     * @return the value of sales_to_do_list.user_name
     *
     * @mbg.generated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_to_do_list.user_name
     *
     * @param userName the value for sales_to_do_list.user_name
     *
     * @mbg.generated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_to_do_list.role_id
     *
     * @return the value of sales_to_do_list.role_id
     *
     * @mbg.generated
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_to_do_list.role_id
     *
     * @param roleId the value for sales_to_do_list.role_id
     *
     * @mbg.generated
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_to_do_list.role_code
     *
     * @return the value of sales_to_do_list.role_code
     *
     * @mbg.generated
     */
    public String getRoleCode() {
        return roleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_to_do_list.role_code
     *
     * @param roleCode the value for sales_to_do_list.role_code
     *
     * @mbg.generated
     */
    public void setRoleCode(String roleCode) {
        this.roleCode = roleCode == null ? null : roleCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_to_do_list.today_num
     *
     * @return the value of sales_to_do_list.today_num
     *
     * @mbg.generated
     */
    public Long getTodayNum() {
        return todayNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_to_do_list.today_num
     *
     * @param todayNum the value for sales_to_do_list.today_num
     *
     * @mbg.generated
     */
    public void setTodayNum(Long todayNum) {
        this.todayNum = todayNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_to_do_list.seven_days_num
     *
     * @return the value of sales_to_do_list.seven_days_num
     *
     * @mbg.generated
     */
    public Long getSevenDaysNum() {
        return sevenDaysNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_to_do_list.seven_days_num
     *
     * @param sevenDaysNum the value for sales_to_do_list.seven_days_num
     *
     * @mbg.generated
     */
    public void setSevenDaysNum(Long sevenDaysNum) {
        this.sevenDaysNum = sevenDaysNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_to_do_list.overdue_num
     *
     * @return the value of sales_to_do_list.overdue_num
     *
     * @mbg.generated
     */
    public Long getOverdueNum() {
        return overdueNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_to_do_list.overdue_num
     *
     * @param overdueNum the value for sales_to_do_list.overdue_num
     *
     * @mbg.generated
     */
    public void setOverdueNum(Long overdueNum) {
        this.overdueNum = overdueNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_to_do_list.create_date
     *
     * @return the value of sales_to_do_list.create_date
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_to_do_list.create_date
     *
     * @param createDate the value for sales_to_do_list.create_date
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_to_do_list
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Task other = (Task) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getOrgCode() == null ? other.getOrgCode() == null : this.getOrgCode().equals(other.getOrgCode()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getUserAccount() == null ? other.getUserAccount() == null : this.getUserAccount().equals(other.getUserAccount()))
            && (this.getUserName() == null ? other.getUserName() == null : this.getUserName().equals(other.getUserName()))
            && (this.getRoleId() == null ? other.getRoleId() == null : this.getRoleId().equals(other.getRoleId()))
            && (this.getRoleCode() == null ? other.getRoleCode() == null : this.getRoleCode().equals(other.getRoleCode()))
            && (this.getTodayNum() == null ? other.getTodayNum() == null : this.getTodayNum().equals(other.getTodayNum()))
            && (this.getSevenDaysNum() == null ? other.getSevenDaysNum() == null : this.getSevenDaysNum().equals(other.getSevenDaysNum()))
            && (this.getOverdueNum() == null ? other.getOverdueNum() == null : this.getOverdueNum().equals(other.getOverdueNum()))
            && (this.getCreateDate() == null ? other.getCreateDate() == null : this.getCreateDate().equals(other.getCreateDate()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_to_do_list
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getOrgCode() == null) ? 0 : getOrgCode().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getUserAccount() == null) ? 0 : getUserAccount().hashCode());
        result = prime * result + ((getUserName() == null) ? 0 : getUserName().hashCode());
        result = prime * result + ((getRoleId() == null) ? 0 : getRoleId().hashCode());
        result = prime * result + ((getRoleCode() == null) ? 0 : getRoleCode().hashCode());
        result = prime * result + ((getTodayNum() == null) ? 0 : getTodayNum().hashCode());
        result = prime * result + ((getSevenDaysNum() == null) ? 0 : getSevenDaysNum().hashCode());
        result = prime * result + ((getOverdueNum() == null) ? 0 : getOverdueNum().hashCode());
        result = prime * result + ((getCreateDate() == null) ? 0 : getCreateDate().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_to_do_list
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", orgCode=").append(orgCode);
        sb.append(", userId=").append(userId);
        sb.append(", userAccount=").append(userAccount);
        sb.append(", userName=").append(userName);
        sb.append(", roleId=").append(roleId);
        sb.append(", roleCode=").append(roleCode);
        sb.append(", todayNum=").append(todayNum);
        sb.append(", sevenDaysNum=").append(sevenDaysNum);
        sb.append(", overdueNum=").append(overdueNum);
        sb.append(", createDate=").append(createDate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}