package com.peace.dao;

import com.peace.entity.PushError;
import com.peace.entity.PushErrorExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PushErrorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_push_error
     *
     * @mbg.generated
     */
    long countByExample(PushErrorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_push_error
     *
     * @mbg.generated
     */
    int deleteByExample(PushErrorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_push_error
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_push_error
     *
     * @mbg.generated
     */
    int insert(PushError record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_push_error
     *
     * @mbg.generated
     */
    int insertSelective(PushError record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_push_error
     *
     * @mbg.generated
     */
    List<PushError> selectByExample(PushErrorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_push_error
     *
     * @mbg.generated
     */
    PushError selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_push_error
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") PushError record, @Param("example") PushErrorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_push_error
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") PushError record, @Param("example") PushErrorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_push_error
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PushError record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_push_error
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PushError record);
}