package com.peace.dao;

import com.peace.entity.TmUser;
import com.peace.entity.TmUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TmUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_user
     *
     * @mbg.generated
     */
    long countByExample(TmUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_user
     *
     * @mbg.generated
     */
    int deleteByExample(TmUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_user
     *
     * @mbg.generated
     */
    int insert(TmUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_user
     *
     * @mbg.generated
     */
    int insertSelective(TmUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_user
     *
     * @mbg.generated
     */
    List<TmUser> selectByExample(TmUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_user
     *
     * @mbg.generated
     */
    TmUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TmUser record, @Param("example") TmUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TmUser record, @Param("example") TmUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TmUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TmUser record);
}